### PR TITLE
57 fix issues related to mao instances and ranktoken

### LINKED ISSUE #57: Fix issues related to MAO instances and RankToken

### PR DESCRIPTION
**Pull request by theKosmoss**
close #57

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -7,17 +7,18 @@
...
 // Utility exports
 export * from "./utils";
 export * from "./types";
 export * from "./rankify/MAODistributor";
+export { default as RankTokenClient } from "./rankify/RankToken";
 
 // Type exports
 export { gameStatusEnum } from "./rankify/InstanceBase";
-export { MAOInstances } from "./types/contracts";
+export { type MAOInstances } from "./types/contracts";
```
Comment (peersky) [inline src/index.ts:21]: these type prefixes seem to be redundant, MAOInstances, NameQuery etc are already interfaces, why casting them in type?

**Review by peersky — APPROVED** [review]
lgtm
